/**
 * NIGHTWIRE — Concept Trailer Beat Sheet
 * Announcement-style previs. Not production game code.
 */

export const STUDIO = {
  name: "MERIDIAN PICTURES INTERACTIVE",
  presents: "A CONCEPT PREVISUALIZATION",
};

export const TITLE = {
  name: "NIGHTWIRE",
  tagline: "The city never sleeps. The truth never stays buried.",
  year: "COMING SOON",
  rating: "M — Mature Investigation",
};

/**
 * Each beat drives camera, overlays, VO, and audio intensity.
 * durationMs is wall-clock for the trailer cut.
 */
export const BEATS = [
  {
    id: "black",
    label: "Studio Card",
    durationMs: 3200,
    scene: "black",
    titleCard: { act: "", title: STUDIO.name, sub: STUDIO.presents },
    vo: null,
    audio: { intensity: 0.05, rain: 0.1 },
  },
  {
    id: "open-rain",
    label: "Neon Rain — Establishing",
    durationMs: 5200,
    scene: "city-aerial",
    caption: "PORT MERIDIAN — 11:47 PM",
    vo: "Voiceover: It always rains when the city wants to hide something.",
    audio: { intensity: 0.25, rain: 0.7 },
    camera: { shot: "crane-down" },
  },
  {
    id: "alley-walk",
    label: "Detective Arrival",
    durationMs: 4800,
    scene: "alley",
    caption: "DETECTIVE MARA QUINN — HOMICIDE, REINSTATED",
    vo: "They pulled me back for a cold case. Said it was paperwork. It never is.",
    audio: { intensity: 0.35, rain: 0.55, footsteps: true },
    camera: { shot: "follow" },
  },
  {
    id: "crime-scene",
    label: "Crime Scene — The Meridian Motel",
    durationMs: 5500,
    scene: "motel",
    caption: "CRIME SCENE — ROOM 214",
    vo: "One missing planner. No body. Blood on the sill that isn't hers.",
    audio: { intensity: 0.45, rain: 0.3 },
    overlays: ["crime-tape", "evidence-markers"],
    camera: { shot: "dolly-in" },
  },
  {
    id: "detective-vision",
    label: "Detective Vision Demo",
    durationMs: 5000,
    scene: "motel-vision",
    caption: "DETECTIVE VISION — ACTIVE",
    vo: "Footprints under the neon. Prints on the glass. A wire behind the wall.",
    audio: { intensity: 0.55, rain: 0.2, sting: true },
    overlays: ["vision-hud", "highlight-clues"],
    camera: { shot: "orbit-slow" },
  },
  {
    id: "photograph",
    label: "Evidence Photography",
    durationMs: 4200,
    scene: "motel",
    caption: "SAMPLE GAMEPLAY — DOCUMENT EVIDENCE",
    vo: null,
    audio: { intensity: 0.4, rain: 0.25, shutter: true },
    overlays: ["camera-ui", "photo-flash"],
    camera: { shot: "pov" },
  },
  {
    id: "inventory",
    label: "Inventory Preview",
    durationMs: 4500,
    scene: "ui-focus",
    caption: "INVENTORY — CASE KIT",
    vo: "Every exhibit logged. Every print tagged. Nothing leaves the board until it talks.",
    audio: { intensity: 0.3, rain: 0.15 },
    overlays: ["inventory-mock"],
  },
  {
    id: "evidence-board",
    label: "Evidence Board Preview",
    durationMs: 5500,
    scene: "board",
    caption: "EVIDENCE BOARD — CONNECT THE WIRE",
    vo: "Connect the motel. The docks. The deputy who filed the wrong report.",
    audio: { intensity: 0.5, rain: 0.1 },
    overlays: ["board-mock"],
    camera: { shot: "board-push" },
  },
  {
    id: "dialogue",
    label: "Interrogation Scene",
    durationMs: 5200,
    scene: "interrogation",
    caption: "INTERVIEW — DET. RUIZ / WITNESS: LENA VOSS",
    vo: null,
    audio: { intensity: 0.4, rain: 0.05 },
    overlays: ["dialogue-choices"],
    camera: { shot: "two-shot" },
  },
  {
    id: "city-drive",
    label: "City Exploration — Drive",
    durationMs: 5000,
    scene: "drive",
    caption: "PORT MERIDIAN — OPEN DISTRICTS",
    vo: "Downtown. The docks. The wire rooms under the train yard.",
    audio: { intensity: 0.55, rain: 0.8, engine: true },
    camera: { shot: "hood-chase" },
  },
  {
    id: "surveillance",
    label: "Tailing / Surveillance",
    durationMs: 4500,
    scene: "rooftop",
    caption: "SURVEILLANCE — DO NOT LOSE THE TAIL",
    vo: "Stay in the rain. Stay off the radio. He knows the frequencies.",
    audio: { intensity: 0.6, rain: 0.5 },
    overlays: ["binocular-ui"],
    camera: { shot: "telephoto" },
  },
  {
    id: "puzzle",
    label: "Puzzle — Lock & Wire",
    durationMs: 4500,
    scene: "lockpick",
    caption: "GAMEPLAY — LOCKPICK / SIGNAL TRACE",
    vo: null,
    audio: { intensity: 0.45, rain: 0.1 },
    overlays: ["lockpick-ui", "hack-ui"],
    camera: { shot: "macro" },
  },
  {
    id: "day-night",
    label: "Day / Night Cycle",
    durationMs: 4800,
    scene: "city-cycle",
    caption: "DYNAMIC WORLD — TIME & WEATHER",
    vo: "Morning briefings. Midnight chases. The city changes its face with the light.",
    audio: { intensity: 0.35, rain: 0.4 },
    camera: { shot: "timelapse" },
  },
  {
    id: "chase",
    label: "Action Sequence",
    durationMs: 4800,
    scene: "chase",
    caption: "ACTION — DOCKYARD PURSUIT",
    vo: "When the wire goes live, you run — or you vanish.",
    audio: { intensity: 0.85, rain: 0.7, chase: true },
    camera: { shot: "handheld" },
  },
  {
    id: "character",
    label: "Character Interaction",
    durationMs: 4500,
    scene: "bar",
    caption: "CHARACTERS — ALLIES, LIARS, AND THE ONES IN BETWEEN",
    vo: "Everyone in Meridian has a schedule. Everyone has a reason to lie.",
    audio: { intensity: 0.4, rain: 0.2 },
    overlays: ["npc-schedule"],
    camera: { shot: "portrait" },
  },
  {
    id: "atmosphere",
    label: "Lighting & Atmosphere",
    durationMs: 4200,
    scene: "neon-street",
    caption: "ATMOSPHERE — WET STREETS / NEON / VOLUMETRIC NIGHT",
    vo: null,
    audio: { intensity: 0.5, rain: 0.85, thunder: true },
    camera: { shot: "low-angle" },
  },
  {
    id: "logo",
    label: "Logo Reveal",
    durationMs: 6500,
    scene: "logo",
    caption: null,
    titleCard: {
      act: "A NEO-NOIR INVESTIGATION",
      title: "NIGHTWIRE",
      sub: "The city never sleeps. The truth never stays buried.",
    },
    vo: null,
    audio: { intensity: 0.7, rain: 0.4, finale: true },
  },
  {
    id: "end-card",
    label: "Approval Gate",
    durationMs: 8000,
    scene: "end",
    caption: null,
    titleCard: {
      act: "CONCEPT PREVISUALIZATION COMPLETE",
      title: "AWAITING YOUR APPROVAL",
      sub: "No production development begins until you greenlight Phase 1 — Game Design Document.",
    },
    vo: null,
    audio: { intensity: 0.2, rain: 0.3 },
    overlays: ["approval-card"],
  },
];

export const DISTRICTS = [
  "Downtown Core",
  "Neon Strip",
  "Harbor Docks",
  "Train Yard / Wire Rooms",
  "Westend Suburbs",
  "Police HQ — Precinct 7",
  "Meridian Motel Row",
  "Factory Belt",
  "Underground Tunnels",
  "Hospital Hill",
];

export const CAST = [
  { name: "Det. Mara Quinn", role: "Protagonist — Reinstated Homicide" },
  { name: "Capt. Elias Boone", role: "Precinct Captain — Political pressure" },
  { name: "Lena Voss", role: "Missing planner's sister — Unreliable ally" },
  { name: "Vince Calder", role: "Dock syndicate fixer — False lead magnet" },
  { name: "Dr. Naomi Park", role: "Forensics — Moral compass" },
];
