import type { LevelDef, SegmentSpec } from '../core/types';

/**
 * 12 original, hand-authored level layouts built from modular pieces.
 * Difficulty ramps from a guided tutorial run to dense high-intensity
 * courses mixing every obstacle type with risk/reward shortcuts.
 */

const s = (type: SegmentSpec['type'], length?: number, params?: Record<string, number>): SegmentSpec => ({
  type,
  ...(length !== undefined ? { length } : {}),
  ...(params !== undefined ? { params } : {}),
});

export const LEVELS: LevelDef[] = [
  {
    id: 1,
    name: 'Brooklyn Start',
    theme: 'rooftop',
    difficulty: 1,
    opponents: 11,
    halfWidth: 6,
    targetTime: 42,
    segments: [
      s('start'),
      s('run', 16),
      s('coinsRun', 20),
      s('speedStrip', 14),
      s('vaultBarrier'),
      s('run', 12),
      s('slideBar'),
      s('coinsRun', 16),
      s('checkpoint'),
      s('gap', 0, { width: 4 }),
      s('speedStrip'),
      s('vaultBarrier'),
      s('powerUp', 12, { type: 0 }),
      s('slideBar'),
      s('checkpoint'),
      s('coinsRun', 18),
      s('gap', 0, { width: 5 }),
      s('run', 14),
      s('finish'),
    ],
  },
  {
    id: 2,
    name: 'Midtown Dash',
    theme: 'street',
    difficulty: 1,
    opponents: 13,
    halfWidth: 6,
    targetTime: 48,
    segments: [
      s('start'),
      s('coinsRun', 18),
      s('vaultBarrier'),
      s('vaultBarrier', 14),
      s('slideBar'),
      s('checkpoint'),
      s('speedStrip'),
      s('breakableWall'),
      s('gap', 0, { width: 5 }),
      s('powerUp', 12, { type: 1 }),
      s('vaultBarrier'),
      s('slideBar', 14),
      s('checkpoint'),
      s('coinsRun', 16),
      s('gap', 0, { width: 6 }),
      s('speedStrip', 14),
      s('vaultBarrier'),
      s('finish'),
    ],
  },
  {
    id: 3,
    name: 'Paris Tiles',
    theme: 'construction',
    difficulty: 2,
    opponents: 14,
    halfWidth: 6,
    targetTime: 55,
    segments: [
      s('start'),
      s('run', 14),
      s('vaultBarrier'),
      s('platforms', 0, { count: 3, gap: 3, platLen: 5 }),
      s('checkpoint'),
      s('slideBar'),
      s('coinsRun', 16),
      s('beams', 0, { len: 20, count: 2 }),
      s('powerUp', 12, { type: 2 }),
      s('checkpoint'),
      s('speedStrip'),
      s('gap', 0, { width: 6 }),
      s('vaultBarrier'),
      s('rampJump', 0, { width: 8 }),
      s('finish'),
    ],
  },
  {
    id: 4,
    name: 'Tokyo Lanes',
    theme: 'street',
    difficulty: 2,
    opponents: 15,
    halfWidth: 6,
    targetTime: 58,
    segments: [
      s('start'),
      s('coinsRun', 16),
      s('wallGap', 0, { width: 10, side: 1 }),
      s('vaultBarrier'),
      s('checkpoint'),
      s('slideBar'),
      s('wallGap', 0, { width: 12, side: -1 }),
      s('powerUp', 12, { type: 0 }),
      s('speedStrip'),
      s('checkpoint'),
      s('breakableWall'),
      s('gap', 0, { width: 6 }),
      s('vaultBarrier'),
      s('sweeper'),
      s('finish'),
    ],
  },
  {
    id: 5,
    name: 'Shanghai Spans',
    theme: 'industrial',
    difficulty: 2,
    opponents: 15,
    halfWidth: 6,
    targetTime: 62,
    segments: [
      s('start'),
      s('run', 14),
      s('sweeper'),
      s('vaultBarrier'),
      s('fallingFloor', 0, { count: 3 }),
      s('checkpoint'),
      s('slideBar'),
      s('movingPlatforms', 0, { count: 2, gap: 3.4 }),
      s('powerUp', 12, { type: 3 }),
      s('checkpoint'),
      s('speedStrip'),
      s('beams', 0, { len: 22, count: 3 }),
      s('vaultBarrier'),
      s('launchPad', 0, { width: 11 }),
      s('finish'),
    ],
  },
  {
    id: 6,
    name: 'Sunset Split',
    theme: 'sunset',
    difficulty: 3,
    opponents: 16,
    halfWidth: 6.2,
    targetTime: 65,
    segments: [
      s('start'),
      s('coinsRun', 16),
      s('split', 0, { len: 32 }),
      s('checkpoint'),
      s('slideBar'),
      s('wallGap', 0, { width: 12, side: 1 }),
      s('vaultBarrier'),
      s('checkpoint'),
      s('split', 0, { len: 34 }),
      s('powerUp', 12, { type: 4 }),
      s('speedStrip'),
      s('gap', 0, { width: 7 }),
      s('sweeper'),
      s('finish'),
    ],
  },
  {
    id: 7,
    name: 'Bridge Blitz',
    theme: 'bridge',
    difficulty: 3,
    opponents: 16,
    halfWidth: 6,
    targetTime: 70,
    segments: [
      s('start'),
      s('speedStrip', 14),
      s('gap', 0, { width: 5 }),
      s('beams', 0, { len: 24, count: 2 }),
      s('checkpoint'),
      s('vaultBarrier'),
      s('movingPlatforms', 0, { count: 3, gap: 3.6 }),
      s('slideBar'),
      s('checkpoint'),
      s('powerUp', 12, { type: 1 }),
      s('wallGap', 0, { width: 13, side: -1 }),
      s('sweeper'),
      s('checkpoint'),
      s('fallingFloor', 0, { count: 4 }),
      s('rampJump', 0, { width: 9 }),
      s('finish'),
    ],
  },
  {
    id: 8,
    name: 'Crane Country',
    theme: 'construction',
    difficulty: 3,
    opponents: 17,
    halfWidth: 6,
    targetTime: 72,
    segments: [
      s('start'),
      s('vaultBarrier', 14),
      s('platforms', 0, { count: 4, gap: 3.4, platLen: 4.5 }),
      s('checkpoint'),
      s('sweeper'),
      s('slideBar'),
      s('breakableWall'),
      s('checkpoint'),
      s('powerUp', 12, { type: 2 }),
      s('fallingFloor', 0, { count: 4 }),
      s('wallGap', 0, { width: 12, side: 1 }),
      s('checkpoint'),
      s('speedStrip'),
      s('split', 0, { len: 34 }),
      s('gap', 0, { width: 7 }),
      s('finish'),
    ],
  },
  {
    id: 9,
    name: 'Neon Tokyo',
    theme: 'night',
    difficulty: 4,
    opponents: 18,
    halfWidth: 6,
    targetTime: 75,
    segments: [
      s('start'),
      s('speedStrip', 14),
      s('slideBar', 14),
      s('vaultBarrier', 13),
      s('sweeper', 20),
      s('checkpoint'),
      s('movingPlatforms', 0, { count: 3, gap: 3.8 }),
      s('powerUp', 12, { type: 3 }),
      s('wallGap', 0, { width: 14, side: -1 }),
      s('checkpoint'),
      s('beams', 0, { len: 24, count: 3 }),
      s('breakableWall'),
      s('checkpoint'),
      s('fallingFloor', 0, { count: 5 }),
      s('launchPad', 0, { width: 12 }),
      s('sweeper', 20),
      s('finish'),
    ],
  },
  {
    id: 10,
    name: 'Rooftop Rush',
    theme: 'rooftop',
    difficulty: 4,
    opponents: 18,
    halfWidth: 6,
    targetTime: 80,
    segments: [
      s('start'),
      s('coinsRun', 14),
      s('gap', 0, { width: 6 }),
      s('vaultBarrier', 12),
      s('slideBar', 12),
      s('checkpoint'),
      s('platforms', 0, { count: 4, gap: 3.6, platLen: 4.4 }),
      s('sweeper', 20),
      s('powerUp', 12, { type: 0 }),
      s('checkpoint'),
      s('split', 0, { len: 36 }),
      s('wallGap', 0, { width: 13, side: 1 }),
      s('checkpoint'),
      s('speedStrip', 14),
      s('breakableWall', 14),
      s('movingPlatforms', 0, { count: 3, gap: 3.8 }),
      s('rampJump', 0, { width: 10 }),
      s('finish'),
    ],
  },
  {
    id: 11,
    name: 'Gauntlet',
    theme: 'industrial',
    difficulty: 5,
    opponents: 19,
    halfWidth: 6,
    targetTime: 85,
    segments: [
      s('start'),
      s('speedStrip', 12),
      s('vaultBarrier', 12),
      s('sweeper', 18),
      s('slideBar', 12),
      s('checkpoint'),
      s('fallingFloor', 0, { count: 5 }),
      s('movingPlatforms', 0, { count: 3, gap: 4 }),
      s('powerUp', 10, { type: 1 }),
      s('checkpoint'),
      s('wallGap', 0, { width: 14, side: -1 }),
      s('beams', 0, { len: 26, count: 2 }),
      s('checkpoint'),
      s('breakableWall', 12),
      s('sweeper', 18),
      s('split', 0, { len: 36 }),
      s('checkpoint'),
      s('gap', 0, { width: 8 }),
      s('launchPad', 0, { width: 13 }),
      s('finish'),
    ],
  },
  {
    id: 12,
    name: 'Skyline Grand Prix',
    theme: 'night',
    difficulty: 5,
    opponents: 20,
    halfWidth: 6.5,
    targetTime: 95,
    segments: [
      s('start'),
      s('speedStrip', 12),
      s('coinsRun', 12),
      s('vaultBarrier', 12),
      s('slideBar', 12),
      s('sweeper', 18),
      s('checkpoint'),
      s('platforms', 0, { count: 5, gap: 3.8, platLen: 4.2 }),
      s('powerUp', 10, { type: 4 }),
      s('wallGap', 0, { width: 14, side: 1 }),
      s('checkpoint'),
      s('split', 0, { len: 38 }),
      s('fallingFloor', 0, { count: 5 }),
      s('checkpoint'),
      s('movingPlatforms', 0, { count: 4, gap: 3.8 }),
      s('breakableWall', 12),
      s('checkpoint'),
      s('beams', 0, { len: 26, count: 3 }),
      s('sweeper', 18),
      s('speedStrip', 12),
      s('rampJump', 0, { width: 11 }),
      s('finish'),
    ],
  },
];

export function getLevel(id: number): LevelDef | undefined {
  return LEVELS.find((l) => l.id === id);
}
