import { CLUES } from "./data.js";

export function emptyPins() {
  return Object.fromEntries(Object.keys(CLUES).map((id) => [id, new Set()]));
}

export function createState() {
  return {
    playing: false,
    locked: false,
    clues: new Set(),
    notes: 0,
    fieldNotes: [],
    pins: emptyPins(),
    unreadEvidence: 0,
    activeClueId: null,
    startTime: 0,
    yaw: 0,
    pitch: 0,
    room: "entrance",
    modalOpen: false,
    journalOpen: false,
    journalTab: "evidence",
    flashlightOn: true,
    battery: 100,
    crouching: false,
    footTimer: 0,
    fov: 72,
    studyUnlocked: false,
    studyDoorT: 0,
    radioFired: new Set(),
    thunderT: 8,
    lookSwayX: 0,
    lookSwayY: 0,
    standY: 1.65,
    timeScale: 1,
    slowMoT: 0,
    studyToastCd: 0,
    exposureBoost: 0,
    accuseReadyAnnounced: false,
    onboardFirstClue: false,
    onboardPinHint: false,
    cinemaBusy: false,
    openingCam: 0,
    openingCamDur: 2.8,
    vx: 0,
    vz: 0,
  };
}

export function resetCaseState(state) {
  Object.assign(state, {
    clues: new Set(),
    notes: 0,
    fieldNotes: [],
    pins: emptyPins(),
    unreadEvidence: 0,
    activeClueId: null,
    startTime: Date.now(),
    yaw: 0,
    pitch: -0.08,
    room: "entrance",
    modalOpen: false,
    journalOpen: false,
    journalTab: "evidence",
    flashlightOn: true,
    battery: 100,
    crouching: false,
    fov: 78,
    studyUnlocked: false,
    studyDoorT: 0,
    radioFired: new Set(),
    thunderT: 6,
    standY: 1.65,
    timeScale: 1,
    slowMoT: 0,
    studyToastCd: 0,
    exposureBoost: 0,
    accuseReadyAnnounced: false,
    onboardFirstClue: false,
    onboardPinHint: false,
    openingCamDur: 2.8,
    openingCam: 2.8,
    vx: 0,
    vz: 0,
  });
}
