#!/usr/bin/env bash
# Full reverse engineering pipeline for Square Android apps
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# shellcheck source=/dev/null
[[ -f "$ROOT_DIR/.env.tools" ]] && source "$ROOT_DIR/.env.tools"

usage() {
  cat <<EOF
Square App Reverse Engineering Pipeline
========================================

Usage: $(basename "$0") <apk-path> [options]

Options:
  --skip-decompile   Run scan only (requires existing output/)
  --skip-scan        Decompile only
  --output DIR       Custom output directory
  -h, --help         Show this help

Steps:
  1. Validate APK and extract package metadata
  2. Decompile with apktool + jadx
  3. Static scan for secrets, endpoints, security controls
  4. Generate analysis report from template

Prerequisites:
  ./scripts/setup.sh

Obtain APK:
  Place com.squareup.apk in apks/ (see docs/methodology.md)

Example:
  $(basename "$0") apks/com.squareup.apk
EOF
}

APK=""
OUT=""
SKIP_DECOMPILE=0
SKIP_SCAN=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    -h|--help) usage; exit 0 ;;
    --skip-decompile) SKIP_DECOMPILE=1; shift ;;
    --skip-scan) SKIP_SCAN=1; shift ;;
    --output) OUT="$2"; shift 2 ;;
    *)
      if [[ -z "$APK" ]]; then
        APK="$1"
      else
        echo "Unknown argument: $1" >&2
        exit 1
      fi
      shift
      ;;
  esac
done

if [[ -z "$APK" ]]; then
  usage
  exit 1
fi

if [[ ! -f "$APK" ]]; then
  echo "Error: APK not found: $APK" >&2
  echo "Download or copy the Square APK to apks/ first." >&2
  exit 1
fi

APK="$(realpath "$APK")"
BASENAME="$(basename "$APK" .apk)"
OUT="${OUT:-$ROOT_DIR/output/$BASENAME}"
OUT="$(realpath -m "$OUT")"

echo "============================================"
echo " Square App Reverse Engineering Pipeline"
echo "============================================"
echo "APK:    $APK"
echo "Output: $OUT"
echo ""

# Step 1: Metadata
echo "[1/4] Extracting APK metadata..."
mkdir -p "$OUT"
if command -v aapt >/dev/null 2>&1; then
  aapt dump badging "$APK" | tee "$OUT/badging.txt"
  PACKAGE="$(aapt dump badging "$APK" | rg -o "package: name='[^']+'" | cut -d"'" -f2 || true)"
  VERSION="$(aapt dump badging "$APK" | rg -o "versionName='[^']+'" | cut -d"'" -f2 || true)"
  echo "Package: ${PACKAGE:-unknown}"
  echo "Version: ${VERSION:-unknown}"
else
  echo "(aapt not available — skipping badging)"
fi

# Step 2: Decompile
if [[ "$SKIP_DECOMPILE" -eq 0 ]]; then
  echo ""
  echo "[2/4] Decompiling..."
  "$ROOT_DIR/scripts/decompile.sh" "$APK" "$OUT"
else
  echo ""
  echo "[2/4] Skipping decompile (--skip-decompile)"
fi

# Step 3: Scan
if [[ "$SKIP_SCAN" -eq 0 ]]; then
  echo ""
  echo "[3/4] Running static scan..."
  "$ROOT_DIR/scripts/scan_secrets.sh" "$OUT"
else
  echo ""
  echo "[3/4] Skipping scan (--skip-scan)"
fi

# Step 4: Report
echo ""
echo "[4/4] Generating analysis report..."
REPORT="$OUT/ANALYSIS.md"
TIMESTAMP="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
SHA256="$(sha256sum "$APK" | awk '{print $1}')"

cat > "$REPORT" <<EOF
# Square App Analysis Report

| Field | Value |
|-------|-------|
| APK | \`$(basename "$APK")\` |
| SHA-256 | \`$SHA256\` |
| Package | ${PACKAGE:-unknown} |
| Version | ${VERSION:-unknown} |
| Analyzed | $TIMESTAMP |

## Artifacts

| Path | Description |
|------|-------------|
| \`jadx/\` | Decompiled Java source |
| \`apktool/\` | Smali + decoded resources |
| \`raw/\` | Unzipped APK |
| \`AndroidManifest.xml\` | Decoded manifest |
| \`scan-report.txt\` | Automated static scan results |

## Next Steps

1. Review \`scan-report.txt\` for endpoints, secrets, and security controls
2. Inspect \`AndroidManifest.xml\` for exported components and deep links
3. Trace POS intent handling: search for \`com.squareup.pos.action.CHARGE\`
4. Run dynamic analysis with Frida hooks in \`frida/\` (see docs/methodology.md)
5. Map network traffic with mitmproxy after SSL pinning bypass

## POS API Surface (public)

Square exposes a documented intent-based POS API. Third-party apps authenticate via
package name + SHA-1 fingerprint registered in the Square Developer Console.

\`\`\`xml
<queries>
  <package android:name="com.squareup" />
</queries>
\`\`\`

See \`docs/intent-api.md\` for full intent contract reference.

---
*Generated by square-re analyze pipeline*
EOF

echo ""
echo "============================================"
echo " Analysis complete"
echo "============================================"
echo "Report:      $REPORT"
echo "Scan:        $OUT/scan-report.txt"
echo "Java source: $OUT/jadx/"
echo ""
echo "For dynamic analysis:"
echo "  frida -U -f com.squareup -l frida/ssl_pinning_bypass.js --no-pause"
