#!/usr/bin/env bash
# Install reverse engineering toolchain for Square app analysis
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TOOLS_DIR="${TOOLS_DIR:-$ROOT_DIR/.tools}"
BIN_DIR="$TOOLS_DIR/bin"

mkdir -p "$BIN_DIR"

log() { printf '[setup] %s\n' "$*"; }
have() { command -v "$1" >/dev/null 2>&1; }

install_jadx() {
  if have jadx || [[ -x "$BIN_DIR/jadx/bin/jadx" ]]; then
    log "jadx already available"
    return
  fi

  local version="1.5.1"
  local url="https://github.com/skylot/jadx/releases/download/v${version}/jadx-${version}.zip"
  local tmp
  tmp="$(mktemp -d)"

  log "Downloading jadx ${version}..."
  curl -fsSL "$url" -o "$tmp/jadx.zip"
  rm -rf "$TOOLS_DIR/jadx"
  mkdir -p "$TOOLS_DIR/jadx"
  unzip -q "$tmp/jadx.zip" -d "$TOOLS_DIR/jadx"
  rm -rf "$tmp"
  log "jadx installed to $TOOLS_DIR/jadx"
}

install_apktool() {
  if have apktool || [[ -x "$BIN_DIR/apktool" ]]; then
    log "apktool already available"
    return
  fi

  local version="2.9.3"
  curl -fsSL \
    "https://raw.githubusercontent.com/iBotPeaches/Apktool/master/scripts/linux/apktool" \
    -o "$BIN_DIR/apktool"
  curl -fsSL \
    "https://github.com/iBotPeaches/Apktool/releases/download/v${version}/apktool_${version}.jar" \
    -o "$BIN_DIR/apktool.jar"
  chmod +x "$BIN_DIR/apktool"
  log "apktool installed to $BIN_DIR"
}

install_uber_apk_signer() {
  if [[ -f "$BIN_DIR/uber-apk-signer.jar" ]]; then
    log "uber-apk-signer already available"
    return
  fi

  local version="1.3.0"
  curl -fsSL \
    "https://github.com/patrickfav/uber-apk-signer/releases/download/v${version}/uber-apk-signer-${version}.jar" \
    -o "$BIN_DIR/uber-apk-signer.jar"
  log "uber-apk-signer installed"
}

install_frida_tools() {
  if have frida || python3 -c "import frida" 2>/dev/null; then
    log "frida already available"
    return
  fi

  log "Installing frida-tools via pip..."
  python3 -m pip install --user frida-tools objection 2>/dev/null || \
    pip3 install --user frida-tools objection
}

install_system_deps() {
  local deps=(curl unzip zip openjdk-17-jre-headless python3 python3-pip adb aapt ripgrep jq)
  local missing=()

  for dep in "${deps[@]}"; do
    if ! dpkg -s "$dep" >/dev/null 2>&1; then
      missing+=("$dep")
    fi
  done

  if ((${#missing[@]} > 0)); then
    log "Installing system packages: ${missing[*]}"
    sudo apt-get update -qq
    sudo apt-get install -y "${missing[@]}"
  fi
}

write_env_file() {
  cat > "$ROOT_DIR/.env.tools" <<EOF
# Generated by scripts/setup.sh — source before running analysis
export SQUARE_RE_ROOT="$ROOT_DIR"
export SQUARE_RE_TOOLS="$TOOLS_DIR"
export PATH="$BIN_DIR:$TOOLS_DIR/jadx/bin:\$PATH"
export APKS="$ROOT_DIR/apks"
export OUTPUT="$ROOT_DIR/output"
EOF
  log "Wrote $ROOT_DIR/.env.tools"
}

main() {
  log "Setting up Square app reverse engineering environment"
  install_system_deps
  install_jadx
  install_apktool
  install_uber_apk_signer
  install_frida_tools
  write_env_file

  mkdir -p "$ROOT_DIR/apks" "$ROOT_DIR/output"

  log ""
  log "Setup complete. Run:"
  log "  source .env.tools"
  log "  ./scripts/analyze.sh apks/com.squareup.apk"
}

main "$@"
